name: stagpus
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  line_awesome_icons: ^1.0.4+2
  flutter_rating_bar: ^3.0.1+1
  curved_navigation_bar: ^0.3.2
  cloud_firestore: ^0.13.7
  image_picker: ^0.6.0+2
  bloc: ^4.0.0
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  email_validator: ^1.0.4
  firebase_auth_web:
  geolocator: ^5.3.2+2
  uuid: ^2.0.0
  image: ^2.0.7
  animator: 0.1.4
  path_provider: ^1.6.7
  google_maps_flutter: ^0.5.24+1
  cupertino_icons: ^0.1.2
  firebase_messaging: ^4.0.0+1
  encrypt: ^4.0.2
  timeago: 2.0.17
  cached_network_image:
  flutter_svg: ^0.18.0
  location: ^3.0.0
  geoflutterfire: ^2.1.0
  flutter_bloc: ^4.0.0
  rxdart: ^0.23.0
  clay_containers: ^0.2.2
  universal_html: ^1.1.0
  url_launcher: ^5.1.2
  table_calendar: ^2.2.3
  gradient_app_bar: ^0.0.1
  flutter_string_encryption: ^0.3.1
  provider: 
  geocoder:
  flutter_map:  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  build_test: ^1.0.0


dependency_overrides:
  flutter_chips_input: ^1.9.0-dev.2
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
    - assets/images/mac.png
    - assets/images/ps5.jpg
    - assets/images/headphones.jpg