name: stagpus
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web: any
  cloud_firestore: ^0.13.4+2
  image_picker: ^0.6.0+2
  firebase_storage: ^3.1.5
  firebase_auth: ^0.15.5+3
  geolocator: 5.3.1
  uuid: ^2.0.0
  image: ^2.0.7
  animator: 0.1.4
  path_provider: ^1.6.7

  cupertino_icons: ^0.1.2
  firebase_messaging: ^4.0.0+1
  timeago: 2.0.17
  cached_network_image:
  flutter_svg: ^0.17.3+1

  universal_html: ^1.1.0
  url_launcher: ^5.1.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_web_test: any
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  test: ^1.3.4

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg